---
:project: katello
:github_org: katello
:prior_releases:
  :3.8.0:
    :redmine_version_id: 356
  :3.7.0:
    :redmine_version_id: 264
  :3.7.1:
    :redmine_version_id: 355
:releases:
  :3.9.0:
    :redmine_version_id: 899
:code_name: New England IPA
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.9
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :katello-installer:
    :branch: KATELLO-3.9
    :repo: https://github.com/Katello/katello-installer.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/1.20
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 0.14.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.3.5
    :repo: https://github.com/Katello/katello-host-tools.git
  :bastion:
    :branch: 6.1.12
    :repo: https://github.com/Katello/bastion.git
  :puppet-pulp:
    :branch: 5.5.0
    :repo: https://github.com/theforeman/puppet-pulp
  :puppet-candlepin:
    :branch: 5.2.2
    :repo: https://github.com/theforeman/puppet-candlepin
  :puppet-certs:
    :branch: 4.3.1
    :repo: https://github.com/theforeman/puppet-certs
  :puppet-qpid:
    :branch: 4.3.1
    :repo: https://github.com/theforeman/puppet-qpid
  :puppet-foreman_proxy_content:
    :branch: 7.2.0
    :repo: https://github.com/theforeman/puppet-foreman_proxy_content
  :puppet-service_wait:
    :branch: 1.0.4
    :repo: https://github.com/theforeman/puppet-service_wait.git
:ignores:
:gpg_key: '10668686'
:mash_scripts:
 - katello-3.9-thirdparty-candlepin-rhel7
 - katello-3.9-rhel7
:tags:
  - name: katello-3.9-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.9-thirdparty-pulp-rhel7
    based_off: katello-thirdparty-pulp-rhel7
    arches:
      - x86_64
  - name: katello-3.9-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.9-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.9-rhel7-override: null
    build_target: katello-3.9-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.9-rhel7-build:
        katello-3.9-rhel7-override: 0
        tfm-ror52-rhel7: 2
        foreman-plugins-1.20-rhel7-override: 3
        foreman-1.20-nonscl-rhel7: 4
        foreman-1.20-rhel7: 10
      katello-3.9-rhel7-override:
        katello-3.9-rhel7: 0
      katello-3.9-rhel7:
        katello-3.9-thirdparty-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
