---
:project: katello
:github_org: katello
:nightly: true
:tags:
  - name: katello-thirdparty-candlepin-rhel7
    based_off: null
    arches:
      - x86_64
  - name: katello-nightly-rhel7
    based_off: null
    helper_tags:
      katello-thirdparty-rhel7: null
      katello-nightly-rhel7-override: null
    build_target: katello-nightly-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-nightly-rhel7-build:
        katello-nightly-rhel7-override: 0
        tfm-ror52-rhel7: 2
        foreman-plugins-nightly-rhel7-override: 3
        foreman-nightly-nonscl-rhel7: 4
        foreman-nightly-rhel7: 10
      katello-nightly-rhel7-override:
        katello-nightly-rhel7: 0
      katello-nightly-rhel7:
        katello-thirdparty-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
